version: '3.8'
services:
  zookeeper-0:
    image: confluentinc/cp-zookeeper:latest
    environment:
      ZOOKEEPER_SERVER_ID: 0
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    volumes:
      - /home/data_spartan/stefanProj/kafka/zk-0:/var/lib/zookeper/data
        # - zoo_1_data:/var/lib/zookeeper/
    ports:
      - 22181:2181
    restart: unless-stopped

  zookeeper-1:
    image: confluentinc/cp-zookeeper:latest
    environment:
      ZOOKEEPER_SERVER_ID: 1
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    volumes:
      - /home/data_spartan/stefanProj/kafka/zk-1:/var/lib/zookeper/data
    ports:
      - 32181:2181
    restart: unless-stopped

  kafka-0:
    image: confluentinc/cp-kafka:latest
    depends_on:
      - zookeeper-0
      - zookeeper-1

    ports:
      - 29092:29092
    restart: unless-stopped
    environment:
      KAFKA_BROKER_ID: 0
      KAFKA_ZOOKEEPER_CONNECT: zookeeper-0:2181,zookeeper-1:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka-0:9092,PLAINTEXT_HOST://localhost:29092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_LOG_RETENTION_HOURS: 96
    volumes:
      - /home/data_spartan/stefanProj/kafka/broker-0:/var/lib/kafka/data
        # - kafka-broker-1:/var/lib/kafka/data

  kafka-1:
    image: confluentinc/cp-kafka:latest
    depends_on:
      - zookeeper-0
      - zookeeper-1
    ports:
      - 39092:39092
    restart: unless-stopped
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper-0:2181,zookeeper-1:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka-1:9092,PLAINTEXT_HOST://localhost:39092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_LOG_RETENTION_HOURS: 96
    volumes:
      - /home/data_spartan/stefanProj/kafka/broker-1:/var/lib/kafka/data

  kafdrop-live-feed:
    container_name: 'live-feed-kafdrop'
    image: obsidiandynamics/kafdrop:latest
    environment:
      - KAFKA_BROKERCONNECT=kafka-0:9092,kafka-1:9092
    ports:
      - 9999:9000
    restart: unless-stopped
    depends_on:
      - kafka-0
      - kafka-1

  mongodb_container:
    image: mongo:latest
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: Stefan123
    ports:
      - 27018:27017
    restart: unless-stopped
    volumes:
      - mongodb:/data/db

volumes:
  # zoo_1_data:
  #   driver: local
  # zoo_2_data:
  #   driver: local
  # kafka-broker-1:
  #   driver: local
  # kafka-broker-2:
  #   driver: local
  mongodb:
    driver: local
